### ISSUE TITLE
Refactor composite actions output

### ISSUE THREAD

**Issue by cmaneu** [microsoft/nubesgen-actions#3]
**Overview of the issue**

The _infrastructure as code_ Terraform composite action is outputing important values as an artifact, called `terraform`, containing a JSON.

However, in able to support bicep deployment as well, we need to move from that mode to something more universal. It'll also allow people to reuse these composite actions outside of the use of NubesGen.

**TODO**
- [ ] Generate outputs for Bicep deployment - See https://github.com/cmaneu/proxyvote/blob/0efc04dfa952221b5f831eab4f2fdffc0d73f24f/.github/workflows/deploy-app.yaml#L55
- [ ] In main repo, update Terraform template to match output names (not `application_caf_name` but `application_name`
- [ ] In main repo, update the github action mustache template. Let the `manage-infrastructure` step declare proper outputs
```yaml
  manage-infrastructure:
    runs-on: ubuntu-20.04
    outputs: 
      application_name: ${{ steps.apply-terraform.outputs.application_name }}
    steps:
      - name: Apply Terraform configuration
        id: apply-terraform
        uses: microsoft/nubesgen-actions/gitops-apply-terraform@3-refactor-composite-actions
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          tf_storage_account: ${{ secrets.TF_STORAGE_ACCOUNT }}
  deploy:
    needs: [manage-infrastructure, build]
    runs-on: ubuntu-20.04
    steps:
      - name: Get outputs
        env: 
          APPNAME: ${{ needs.manage-infrastructure.outputs.application_name }}
        run: echo '$APPNAME'
        shell: bash
      - run: echo '${{ toJson(needs) }}'
        shell: bash        
      - name: Deploy a .NET application to Azure App Service
        uses: microsoft/nubesgen-actions/gitops-deploy-to-app-service-dotnet@3-refactor-composite-actions
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          application_name: ${{ needs.manage-infrastructure.outputs.application_name }}
```
- [ ] Update all deployment composite actions
- [ ] Remove debug toJson steps
